server:
 port: 8090
spring:
   jackson:
     time-zone: GMT+8
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/erbendao?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
   jpa:
      database: MYSQL
      show-sql: true
      generate-ddl: true
   mail:
      host: smtp.qq.com
      username: 297966645@qq.com
      password: viwusorzsxjtbhij
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
      default-encoding: UTF-8
   servlet:
     multipart:
       max-file-size: 10MB
       max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qf.pojo

qiniu:
  ak: AWpCqQEY9qvOMbmguZsIJaA5T6EoGdC5Ywim4oKU
  sk: BU7fgwT675Ka7MJX1B2SSxy3rrdp9fNSyX8_ZyC-
  bucket: donycode
  url: http://qkuw9yntd.hb-bkt.clouddn.com/

